name: Go

on:
  push:
    tags:
      - 'v*.*.*'
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build Windows
      run: env GOOS=windows GOARCH=amd64 go build -o geofabrik.exe -v ./cmd/cli/main.go

    - name: Build Linux x64
      run: env GOOS=linux GOARCH=amd64 go build -o geofabrik -v ./cmd/cli/main.go

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files:
          geofabrik.exe
          geofabrik
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Test
      run: go test -v ./...
