name: Go

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build Windows
        run: env GOOS=windows GOARCH=amd64 go build -o osm.exe -v cmd/cli/main.go

      - name: Build Linux x64
        run: env GOOS=linux GOARCH=amd64 go build -o osm cmd/cli/main.go

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: osm.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
